// <auto-generated>
// Rewired Constants
// This list was generated on 5/31/2022 9:03:37 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

public static partial class PlayerAction {
    // Default
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MoveHorizontal")]
    public const int MoveHorizontal = 0;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MoveVertical")]
    public const int MoveVertical = 1;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Attack")]
    public const int Attack = 2;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Evade")]
    public const int Evade = 3;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "LockOn")]
    public const int LockOn = 4;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "LookHorizontal")]
    public const int LookHorizontal = 5;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "LookVertical")]
    public const int LookVertical = 6;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Jump")]
    public const int Jump = 11;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "SlowMo")]
    public const int SlowMo = 14;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Pause")]
    public const int Pause = 7;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Confirm")]
    public const int Confirm = 8;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Cancel")]
    public const int Cancel = 9;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MenuHorizontal")]
    public const int MenuHorizontal = 12;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MenuVertical")]
    public const int MenuVertical = 13;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "SwitchPlayer")]
    public const int SwitchPlayer = 15;
}
